version: '3'

# vars:
#   GREETING: Hello, world!

tasks:
  install-deps:
    desc: Install Buf and protoc plugins
    cmds:
      - go install github.com/bufbuild/buf/cmd/buf@latest
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest

  proto:
    desc: Generate protobuf, gRPC and gateway via Buf
    cmds:
      - buf mod update
      - buf generate