// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/proto/lab.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	CpuLimit      float64                `protobuf:"fixed64,2,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	RamLimitMb    int64                  `protobuf:"varint,3,opt,name=ram_limit_mb,json=ramLimitMb,proto3" json:"ram_limit_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabRequest) Reset() {
	*x = LabRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabRequest) ProtoMessage() {}

func (x *LabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabRequest.ProtoReflect.Descriptor instead.
func (*LabRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{0}
}

func (x *LabRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *LabRequest) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *LabRequest) GetRamLimitMb() int64 {
	if x != nil {
		return x.RamLimitMb
	}
	return 0
}

type LabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabResponse) Reset() {
	*x = LabResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabResponse) ProtoMessage() {}

func (x *LabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabResponse.ProtoReflect.Descriptor instead.
func (*LabResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{1}
}

func (x *LabResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_lab_proto protoreflect.FileDescriptor

const file_api_proto_lab_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/lab.proto\x12\x03lab\"a\n" +
	"\n" +
	"LabRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1b\n" +
	"\tcpu_limit\x18\x02 \x01(\x01R\bcpuLimit\x12 \n" +
	"\fram_limit_mb\x18\x03 \x01(\x03R\n" +
	"ramLimitMb\"0\n" +
	"\vLabResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"0\n" +
	"\vStopRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2k\n" +
	"\n" +
	"LabService\x12-\n" +
	"\bStartLab\x12\x0f.lab.LabRequest\x1a\x10.lab.LabResponse\x12.\n" +
	"\aStopLab\x12\x10.lab.StopRequest\x1a\x11.lab.StopResponseB:Z8github.com/ellipse/kernel-lab/internal/transport/grpc/pbb\x06proto3"

var (
	file_api_proto_lab_proto_rawDescOnce sync.Once
	file_api_proto_lab_proto_rawDescData []byte
)

func file_api_proto_lab_proto_rawDescGZIP() []byte {
	file_api_proto_lab_proto_rawDescOnce.Do(func() {
		file_api_proto_lab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_lab_proto_rawDesc), len(file_api_proto_lab_proto_rawDesc)))
	})
	return file_api_proto_lab_proto_rawDescData
}

var file_api_proto_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_lab_proto_goTypes = []any{
	(*LabRequest)(nil),   // 0: lab.LabRequest
	(*LabResponse)(nil),  // 1: lab.LabResponse
	(*StopRequest)(nil),  // 2: lab.StopRequest
	(*StopResponse)(nil), // 3: lab.StopResponse
}
var file_api_proto_lab_proto_depIdxs = []int32{
	0, // 0: lab.LabService.StartLab:input_type -> lab.LabRequest
	2, // 1: lab.LabService.StopLab:input_type -> lab.StopRequest
	1, // 2: lab.LabService.StartLab:output_type -> lab.LabResponse
	3, // 3: lab.LabService.StopLab:output_type -> lab.StopResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_lab_proto_init() }
func file_api_proto_lab_proto_init() {
	if File_api_proto_lab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_lab_proto_rawDesc), len(file_api_proto_lab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_lab_proto_goTypes,
		DependencyIndexes: file_api_proto_lab_proto_depIdxs,
		MessageInfos:      file_api_proto_lab_proto_msgTypes,
	}.Build()
	File_api_proto_lab_proto = out.File
	file_api_proto_lab_proto_goTypes = nil
	file_api_proto_lab_proto_depIdxs = nil
}
