// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/lab.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterLabRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LabId           string                 `protobuf:"bytes,1,opt,name=lab_id,json=labId,proto3" json:"lab_id,omitempty"`
	Image           string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	InitialCode     string                 `protobuf:"bytes,3,opt,name=initial_code,json=initialCode,proto3" json:"initial_code,omitempty"`
	JudgeCode       string                 `protobuf:"bytes,4,opt,name=judge_code,json=judgeCode,proto3" json:"judge_code,omitempty"`
	JudgeType       string                 `protobuf:"bytes,5,opt,name=judge_type,json=judgeType,proto3" json:"judge_type,omitempty"`
	CpuLimit        float64                `protobuf:"fixed64,6,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	RamLimitMb      int64                  `protobuf:"varint,7,opt,name=ram_limit_mb,json=ramLimitMb,proto3" json:"ram_limit_mb,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterLabRequest) Reset() {
	*x = RegisterLabRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLabRequest) ProtoMessage() {}

func (x *RegisterLabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLabRequest.ProtoReflect.Descriptor instead.
func (*RegisterLabRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterLabRequest) GetLabId() string {
	if x != nil {
		return x.LabId
	}
	return ""
}

func (x *RegisterLabRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RegisterLabRequest) GetInitialCode() string {
	if x != nil {
		return x.InitialCode
	}
	return ""
}

func (x *RegisterLabRequest) GetJudgeCode() string {
	if x != nil {
		return x.JudgeCode
	}
	return ""
}

func (x *RegisterLabRequest) GetJudgeType() string {
	if x != nil {
		return x.JudgeType
	}
	return ""
}

func (x *RegisterLabRequest) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *RegisterLabRequest) GetRamLimitMb() int64 {
	if x != nil {
		return x.RamLimitMb
	}
	return 0
}

func (x *RegisterLabRequest) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type RegisterLabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LabId         string                 `protobuf:"bytes,2,opt,name=lab_id,json=labId,proto3" json:"lab_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLabResponse) Reset() {
	*x = RegisterLabResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLabResponse) ProtoMessage() {}

func (x *RegisterLabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLabResponse.ProtoReflect.Descriptor instead.
func (*RegisterLabResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterLabResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterLabResponse) GetLabId() string {
	if x != nil {
		return x.LabId
	}
	return ""
}

type LabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabId         string                 `protobuf:"bytes,1,opt,name=lab_id,json=labId,proto3" json:"lab_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabRequest) Reset() {
	*x = LabRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabRequest) ProtoMessage() {}

func (x *LabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabRequest.ProtoReflect.Descriptor instead.
func (*LabRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{2}
}

func (x *LabRequest) GetLabId() string {
	if x != nil {
		return x.LabId
	}
	return ""
}

type LabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	InitialCode   string                 `protobuf:"bytes,2,opt,name=initial_code,json=initialCode,proto3" json:"initial_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabResponse) Reset() {
	*x = LabResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabResponse) ProtoMessage() {}

func (x *LabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabResponse.ProtoReflect.Descriptor instead.
func (*LabResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{3}
}

func (x *LabResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LabResponse) GetInitialCode() string {
	if x != nil {
		return x.InitialCode
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_api_proto_lab_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalInput) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalInput) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalInput) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_api_proto_lab_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{7}
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerId    string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{8}
}

func (x *ExecRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExecRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{9}
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	DestPath      string                 `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *UploadFileRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ExtendLabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ExtendSeconds int64                  `protobuf:"varint,2,opt,name=extend_seconds,json=extendSeconds,proto3" json:"extend_seconds,omitempty"` // how many seconds to extend (e.g., 900 for 15 min)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendLabRequest) Reset() {
	*x = ExtendLabRequest{}
	mi := &file_api_proto_lab_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendLabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendLabRequest) ProtoMessage() {}

func (x *ExtendLabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendLabRequest.ProtoReflect.Descriptor instead.
func (*ExtendLabRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{12}
}

func (x *ExtendLabRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExtendLabRequest) GetExtendSeconds() int64 {
	if x != nil {
		return x.ExtendSeconds
	}
	return 0
}

type ExtendLabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewTtlSeconds int64                  `protobuf:"varint,2,opt,name=new_ttl_seconds,json=newTtlSeconds,proto3" json:"new_ttl_seconds,omitempty"` // remaining TTL after extension
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendLabResponse) Reset() {
	*x = ExtendLabResponse{}
	mi := &file_api_proto_lab_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendLabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendLabResponse) ProtoMessage() {}

func (x *ExtendLabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_lab_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendLabResponse.ProtoReflect.Descriptor instead.
func (*ExtendLabResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_lab_proto_rawDescGZIP(), []int{13}
}

func (x *ExtendLabResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExtendLabResponse) GetNewTtlSeconds() int64 {
	if x != nil {
		return x.NewTtlSeconds
	}
	return 0
}

func (x *ExtendLabResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_api_proto_lab_proto protoreflect.FileDescriptor

const file_api_proto_lab_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/lab.proto\x12\x03lab\x1a\x1cgoogle/api/annotations.proto\"\x8c\x02\n" +
	"\x12RegisterLabRequest\x12\x15\n" +
	"\x06lab_id\x18\x01 \x01(\tR\x05labId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12!\n" +
	"\finitial_code\x18\x03 \x01(\tR\vinitialCode\x12\x1d\n" +
	"\n" +
	"judge_code\x18\x04 \x01(\tR\tjudgeCode\x12\x1d\n" +
	"\n" +
	"judge_type\x18\x05 \x01(\tR\tjudgeType\x12\x1b\n" +
	"\tcpu_limit\x18\x06 \x01(\x01R\bcpuLimit\x12 \n" +
	"\fram_limit_mb\x18\a \x01(\x03R\n" +
	"ramLimitMb\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x03R\x0fdurationSeconds\"F\n" +
	"\x13RegisterLabResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06lab_id\x18\x02 \x01(\tR\x05labId\"#\n" +
	"\n" +
	"LabRequest\x12\x15\n" +
	"\x06lab_id\x18\x01 \x01(\tR\x05labId\"S\n" +
	"\vLabResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12!\n" +
	"\finitial_code\x18\x02 \x01(\tR\vinitialCode\"0\n" +
	"\vStopRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"n\n" +
	"\rTerminalInput\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"$\n" +
	"\x0eTerminalOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"m\n" +
	"\vExecRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"[\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\x89\x01\n" +
	"\x11UploadFileRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\tdest_path\x18\x02 \x01(\tR\bdestPath\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"K\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"\\\n" +
	"\x10ExtendLabRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0eextend_seconds\x18\x02 \x01(\x03R\rextendSeconds\"r\n" +
	"\x11ExtendLabResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fnew_ttl_seconds\x18\x02 \x01(\x03R\rnewTtlSeconds\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg2\xd9\x04\n" +
	"\n" +
	"LabService\x12U\n" +
	"\vRegisterLab\x12\x17.lab.RegisterLabRequest\x1a\x18.lab.RegisterLabResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/labs\x12Q\n" +
	"\bStartLab\x12\x0f.lab.LabRequest\x1a\x10.lab.LabResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/labs/{lab_id}/start\x12U\n" +
	"\aStopLab\x12\x10.lab.StopRequest\x1a\x11.lab.StopResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/containers/{container_id}\x12=\n" +
	"\x0eTerminalStream\x12\x12.lab.TerminalInput\x1a\x13.lab.TerminalOutput(\x010\x01\x12`\n" +
	"\tExecCheck\x12\x10.lab.ExecRequest\x1a\x11.lab.ExecResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/containers/{container_id}/check\x12m\n" +
	"\n" +
	"UploadFile\x12\x16.lab.UploadFileRequest\x1a\x17.lab.UploadFileResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/containers/{container_id}/files\x12:\n" +
	"\tExtendLab\x12\x15.lab.ExtendLabRequest\x1a\x16.lab.ExtendLabResponseB)Z'github.com/ellipse/kernel-lab/api/protob\x06proto3"

var (
	file_api_proto_lab_proto_rawDescOnce sync.Once
	file_api_proto_lab_proto_rawDescData []byte
)

func file_api_proto_lab_proto_rawDescGZIP() []byte {
	file_api_proto_lab_proto_rawDescOnce.Do(func() {
		file_api_proto_lab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_lab_proto_rawDesc), len(file_api_proto_lab_proto_rawDesc)))
	})
	return file_api_proto_lab_proto_rawDescData
}

var file_api_proto_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_lab_proto_goTypes = []any{
	(*RegisterLabRequest)(nil),  // 0: lab.RegisterLabRequest
	(*RegisterLabResponse)(nil), // 1: lab.RegisterLabResponse
	(*LabRequest)(nil),          // 2: lab.LabRequest
	(*LabResponse)(nil),         // 3: lab.LabResponse
	(*StopRequest)(nil),         // 4: lab.StopRequest
	(*StopResponse)(nil),        // 5: lab.StopResponse
	(*TerminalInput)(nil),       // 6: lab.TerminalInput
	(*TerminalOutput)(nil),      // 7: lab.TerminalOutput
	(*ExecRequest)(nil),         // 8: lab.ExecRequest
	(*ExecResponse)(nil),        // 9: lab.ExecResponse
	(*UploadFileRequest)(nil),   // 10: lab.UploadFileRequest
	(*UploadFileResponse)(nil),  // 11: lab.UploadFileResponse
	(*ExtendLabRequest)(nil),    // 12: lab.ExtendLabRequest
	(*ExtendLabResponse)(nil),   // 13: lab.ExtendLabResponse
}
var file_api_proto_lab_proto_depIdxs = []int32{
	0,  // 0: lab.LabService.RegisterLab:input_type -> lab.RegisterLabRequest
	2,  // 1: lab.LabService.StartLab:input_type -> lab.LabRequest
	4,  // 2: lab.LabService.StopLab:input_type -> lab.StopRequest
	6,  // 3: lab.LabService.TerminalStream:input_type -> lab.TerminalInput
	8,  // 4: lab.LabService.ExecCheck:input_type -> lab.ExecRequest
	10, // 5: lab.LabService.UploadFile:input_type -> lab.UploadFileRequest
	12, // 6: lab.LabService.ExtendLab:input_type -> lab.ExtendLabRequest
	1,  // 7: lab.LabService.RegisterLab:output_type -> lab.RegisterLabResponse
	3,  // 8: lab.LabService.StartLab:output_type -> lab.LabResponse
	5,  // 9: lab.LabService.StopLab:output_type -> lab.StopResponse
	7,  // 10: lab.LabService.TerminalStream:output_type -> lab.TerminalOutput
	9,  // 11: lab.LabService.ExecCheck:output_type -> lab.ExecResponse
	11, // 12: lab.LabService.UploadFile:output_type -> lab.UploadFileResponse
	13, // 13: lab.LabService.ExtendLab:output_type -> lab.ExtendLabResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_lab_proto_init() }
func file_api_proto_lab_proto_init() {
	if File_api_proto_lab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_lab_proto_rawDesc), len(file_api_proto_lab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_lab_proto_goTypes,
		DependencyIndexes: file_api_proto_lab_proto_depIdxs,
		MessageInfos:      file_api_proto_lab_proto_msgTypes,
	}.Build()
	File_api_proto_lab_proto = out.File
	file_api_proto_lab_proto_goTypes = nil
	file_api_proto_lab_proto_depIdxs = nil
}
