// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: api/proto/lab.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LabService_StartLab_FullMethodName = "/lab.LabService/StartLab"
	LabService_StopLab_FullMethodName  = "/lab.LabService/StopLab"
)

// LabServiceClient is the client API for LabService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LabServiceClient interface {
	StartLab(ctx context.Context, in *LabRequest, opts ...grpc.CallOption) (*LabResponse, error)
	StopLab(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type labServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLabServiceClient(cc grpc.ClientConnInterface) LabServiceClient {
	return &labServiceClient{cc}
}

func (c *labServiceClient) StartLab(ctx context.Context, in *LabRequest, opts ...grpc.CallOption) (*LabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LabResponse)
	err := c.cc.Invoke(ctx, LabService_StartLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labServiceClient) StopLab(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, LabService_StopLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabServiceServer is the server API for LabService service.
// All implementations must embed UnimplementedLabServiceServer
// for forward compatibility.
type LabServiceServer interface {
	StartLab(context.Context, *LabRequest) (*LabResponse, error)
	StopLab(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedLabServiceServer()
}

// UnimplementedLabServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLabServiceServer struct{}

func (UnimplementedLabServiceServer) StartLab(context.Context, *LabRequest) (*LabResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLab not implemented")
}
func (UnimplementedLabServiceServer) StopLab(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopLab not implemented")
}
func (UnimplementedLabServiceServer) mustEmbedUnimplementedLabServiceServer() {}
func (UnimplementedLabServiceServer) testEmbeddedByValue()                    {}

// UnsafeLabServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabServiceServer will
// result in compilation errors.
type UnsafeLabServiceServer interface {
	mustEmbedUnimplementedLabServiceServer()
}

func RegisterLabServiceServer(s grpc.ServiceRegistrar, srv LabServiceServer) {
	// If the following call panics, it indicates UnimplementedLabServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LabService_ServiceDesc, srv)
}

func _LabService_StartLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabServiceServer).StartLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabService_StartLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabServiceServer).StartLab(ctx, req.(*LabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabService_StopLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabServiceServer).StopLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LabService_StopLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabServiceServer).StopLab(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LabService_ServiceDesc is the grpc.ServiceDesc for LabService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LabService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lab.LabService",
	HandlerType: (*LabServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartLab",
			Handler:    _LabService_StartLab_Handler,
		},
		{
			MethodName: "StopLab",
			Handler:    _LabService_StopLab_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/lab.proto",
}
